# Requisição GET
GET http://localhost:3000/alunos

###

# Requisição POST
POST http://localhost:3000/alunos
Content-Type: application/json

{
  "nome": "admin",
  "senha": "admin123",
  "cod_curso": 1,
  "email": "admin@gmail.com",
  "data_nascimento":"2004-10-12T00:00:00.000Z",
  "situacao_aluno": "Matriculado"
}


###

# Requisição DELETE
DELETE http://localhost:3000/alunos/1

###

# Requisição PUT

PUT http://localhost:3000/alunos/4
Content-Type: application/json

{
  "nome": "admin",
  "senha": "$2b$10$jruQOXMfw7B0MN7tIfFw4O5SWZ4qizKDXG50FMxJM4SGeF7rXhC/2",
  "cod_curso": 2,
  "email": "teste@admin.com",
  "data_nascimento": "2004-10-12T00:00:00.000Z",
  "data_inscricao": "2024-09-11T00:00:00.000Z",
  "situacao_aluno": "Matriculado"
}

###

# Login

POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "senha": "admin123"
}