# Requisição GET
GET http://localhost:3000/alunos

###

# Requisição POST
POST http://localhost:3000/alunos
Content-Type: application/json

{
  "nome": "Leonardo Prado",
  "cod_curso": 1,
  "email": "LeonardoPrado@example.com",
  "data_nascimento":"2024-10-01",
  "situacao_aluno": "Matriculado"
}


###

# Requisição DELETE
DELETE http://localhost:3000/alunos/9

###

# Requisição PUT

PUT http://localhost:3000/alunos/10
Content-Type: application/json

{
  "nome": "Leonardo Prado de Alvarenga",
  "cod_curso": 1,
  "email": "LeonardoPrado@example.com",
  "data_nascimento":"2024-10-01",
  "situacao_aluno": "Matriculado"
}